server:
  port : 8080
spring:
  application:
    name: "Formalizacao Backoffice"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: f1234
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true